/// Flutter icons SpaceIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpaceIcons
///      fonts:
///       - asset: fonts/SpaceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpaceIcons {
  SpaceIcons._();

  static const _kFontFam = 'SpaceIcons';
  static const _kFontPkg = null;

  static const IconData astronaut = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iss = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space_module = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telescope = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
