name: iss_tracker_v2
description: "An app to track the current, and future location of the Internation Space station.
Uses data scraped from NASA, the app notifies the user of an upcoming ISS pass over their location,
displays some stats about the craft, the number of people onboard at any given moment, it's coords, etc."

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.9.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.27+3
  http: ^0.12.1
  location: ^3.0.2
  flutter_beautiful_popup: ^1.5.0
  settings_ui: ^0.1.1
  webview_flutter: ^0.3.22+1
  store_redirect: ^1.0.2
  youtube_player_flutter: ^7.0.0+6
  url_launcher: ^5.4.11
  package_info: ^0.4.1
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/astronaut.svg
    - assets/images/iss.svg
    - assets/images/iss.png
    - assets/images/satellite.svg
    - assets/images/space-module.svg
    - assets/images/telescope.svg


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

    - family: SpaceIcons
      fonts:
        - asset: assets/fonts/SpaceIcons.ttf